# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_prn/design_prn.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_prn || ORIG_REF_NAME==design_prn} -quiet] -quiet

# IP: bd/design_prn/ip/design_prn_processing_system7_0_0/design_prn_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_prn_processing_system7_0_0 || ORIG_REF_NAME==design_prn_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_prn/ip/design_prn_PRN_Data_Gen_IP_0_0/design_prn_PRN_Data_Gen_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_prn_PRN_Data_Gen_IP_0_0 || ORIG_REF_NAME==design_prn_PRN_Data_Gen_IP_0_0} -quiet] -quiet

# IP: bd/design_prn/ip/design_prn_auto_pc_0/design_prn_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_prn_auto_pc_0 || ORIG_REF_NAME==design_prn_auto_pc_0} -quiet] -quiet

# IP: bd/design_prn/ip/design_prn_ps7_0_axi_periph_0/design_prn_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_prn_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_prn_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_prn/ip/design_prn_rst_ps7_0_50M_0/design_prn_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_prn_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_prn_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/design_prn/design_prn_ooc.xdc
